### ISSUE TITLE
[awesome-usecase] zeroturnaround

### ISSUE THREAD

**Issue by koolhead17** [minio/awesome-minio#33]
We're building an APM (Application Performance Monitoring) tool https://zeroturnaround.com/software/xrebel-hub/ and we're going to provide an on-premise option.
Since out data storage is S3-based, we were looking for some on-premise replacements and decided to use Minio because we were using it already for the integration testing.

But we're happy to officially admit that we use Minio =) At least right now it's absolutely public that it helps us to run our integration tests

**Comment by kannappanr** [comment]
Closing the issue, as we do not have enough information to document in a usecase
