### ISSUE TITLE
Adding gof3r to the list.

### ISSUE THREAD

**Issue by koolhead17** [minio/awesome-minio#45]
Harsha has sent a PR to gof3r project https://github.com/rlmcpherson/s3gof3r/pull/111/commits/8eb9bb6e0ab81430519d756d901a18247e254be6  

Adding it here as a placeholder, we can add it to our list after we patch is merged and we test it.

**Comment by kannappanr** [comment]
Closing this issue now. Will re-open this when we have cycles to look into this issue.Closing this issue now. Will re-open this when we have cycles to look into this issue.
