### ISSUE TITLE
Add  scrapy_quotes to the awesome-tools list

### ISSUE THREAD

**Issue by koolhead17** [minio/awesome-minio#57]
We should also add [scrapy_quotes](https://bitbucket.org/drozdyuk/scrapy_quotes/src/94b44753cd33e8bd996d4e292a4666b6f7f682a0/scrapy_quotes/?at=master) to our list. 

Reference: [StackOverflow](http://stackoverflow.com/questions/8911162/scrapy-custom-exporter/41973194#41973194)

**Comment by kannappanr** [comment]
Closing this issue now. Will re-open this when we have cycles to look into this issue.
